strassen: strassen.cpp
	g++ -Wall -g -o programas/strassen strassen.cpp

simple: simple.cpp
	g++ -Wall -g -o programas/simple simple.cpp

transpuesta: transpuesta.cpp
	g++ -Wall -g -o programas/transpuesta transpuesta.cpp

make_all: strassen simple transpuesta

make: make_all

clean:
	rm programas/strassen
	rm programas/simple
	rm programas/transpuesta
