selection_sort: selection_sort.cpp
	g++ -Wall -g -o programas/selection_sort selection_sort.cpp

merge_sort: merge_sort.cpp
	g++ -Wall -g -o programas/merge_sort merge_sort.cpp

quick_sort: quick_sort.cpp
	g++ -Wall -g -o programas/quick_sort quick_sort.cpp

funcion_implementada: funcion_implementada.cpp
	g++ -Wall -g -o programas/funcion_implementada funcion_implementada.cpp

make_all: selection_sort merge_sort quick_sort funcion_implementada

clean:
	rm ./programas/merge_sort
	rm ./programas/selection_sort
	rm ./programas/quick_sort
	rm ./programas/funcion_implementada
